jobs:
 - job: main
   displayName: Compile and test
   dependsOn: []
   pool:
     vmImage: windows-2022
   steps:
     - script: |
               curl -sSf -o rustup-init.exe https://win.rustup.rs
               rustup-init.exe -y --profile minimal --default-toolchain %RUSTUP_TOOLCHAIN% --default-host x86_64-pc-windows-msvc
               set PATH=%PATH%;%USERPROFILE%\.cargo\bin
               echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
       displayName: Install Rust
     - script: cargo fmt --all -- --check
       displayName: cargo fmt --check
     - script: cargo clippy --all
       displayName: cargo clippy -- -D warnings
     # Run any user-specific setup steps
     - script: cargo run --package ioring-rs --example readme --all-features 
       displayName: cargo example readme
     - script: cargo run --package ioring-rs --example tcp_echo --all-features 
       displayName: cargo example tcp_echo
     - script: cargo run --package ioring-rs --example raw_api_read --all-features 
       displayName: cargo example raw_api_read
     - script: cargo doc --no-deps
       displayName: cargo doc
